version: '3'
services:
  app:
    build: ./
    ports:
      - "8003:8003"
      - "9003:9003"
      - "10003:10003"
    expose:
      - 8003
      - 9003
      - 10003
    volumes:
      - ./:/app
      - /app/target
      - /app/project/project
      - /app/project/target
    container_name: duel-links-api
    stdin_open: true
    tty: true
    env_file:
      - ./.env